name: Create Release

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: "Version to release (example: 1.0.2)"
        required: true
        type: string

jobs:
  prepare-release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - name: Print release info
        run: |
          echo "::notice::Release v${{ inputs.versionName }} from branch ${{ github.ref_name }}"
      # - uses: actions-ecosystem/action-bump-semver@v1
      #   id: bump-semver
      #   with:
      #     current_version: ${{ inputs.versionName }}
      #     level: patch
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup git user
        run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Set version and commit changes
        run: |
          git tag -a ${{ inputs.versionName }} -m "Release v${{ inputs.versionName }}"
      - name: Push changes
        run: git push && git push --tags
      - name: Trigger workflow to generate release
        uses: actions/github-script@v6
        with:
          # This workflow is not triggered automatically because the tag is pushed with a workflow github_token, so we trigger it manually
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'CreateRelease.yaml',
              ref: '${{ inputs.versionName }}',
            })

  call-build-workflow:
    name: Build
    uses: lomination/ReConnect/.github/workflows/BuildForAllPlateforms.yaml@main
    with:
      versionName: ${{ inputs.versionName }}
    secrets: inherit
